### ISSUE TITLE
Some suggestions for improving user experience

### ISSUE THREAD

**Issue by skyeKing** [QuadSpinner/Gaea-Quickstarts#1]
1) As a novice, it is difficult to understand what a node does by identifying its name. Especially as a native speaker who is not English. Can you make some icons or prompt boxes to outline what this node does?
2) There will be a small delay in adjusting the three-dimensional view after the operation of other panels. Can we optimize it?
3) The boundary between the panels in the window is not obvious, so it is not easy to adjust the panel size by dragging the boundary.
4) Extra minor requirements that may be a little too small to support Python

**Comment by daxpandhi** [comment]
Hi. For software related issues, you need to open a ticket at https://quadspinner.com/support 

I've gone ahead and opened issues on your behalf in our internal bug tracker for the relevant items.

1. Documentation-style tooltips will be coming to the nodes very soon.
2. Not at the moment. If you're experiencing extremely long delays, you may want to turn on "Optiimize visuals" in Preferences.
3. I've logged this issue in the internal bug tracker.
4. We will not be implementing Python in Gaea, however other scripting and SDK options are planned for the future.

Thanks :)
